// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudokuServer.Models.DatabaseModels.Context;

#nullable disable

namespace SudokuServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251012113130_AutoUpdateTime")]
    partial class AutoUpdateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SudokuServer.Models.DatabaseModels.Models.SudokuGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasComment("数独游戏id");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("数独游戏版块");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasComment("数独游戏创建时间");

                    b.Property<int>("Seed")
                        .HasColumnType("int")
                        .HasComment("数独游戏随机种子");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasComment("数独游戏版块大小");

                    b.Property<string>("StartBoard")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("数独游戏开始时的版块");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("数独游戏类型");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("数独游戏最后更新时间");

                    b.Property<string>("WinBoard")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("数独游戏获胜时的版块");

                    b.HasKey("Id");

                    b.ToTable("SudokuGames");
                });
#pragma warning restore 612, 618
        }
    }
}
