// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudokuServer.Models.DatabaseModels.Context;

#nullable disable

namespace SudokuServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251012104315_UpdateCreateTime")]
    partial class UpdateCreateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SudokuServer.Models.DatabaseModels.Models.SudokuGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("数独游戏id");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2)
                        .HasComment("数独游戏版块");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("数独游戏创建时间");

                    b.Property<int>("Seed")
                        .HasColumnType("int")
                        .HasColumnOrder(4)
                        .HasComment("数独游戏随机种子");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnOrder(5)
                        .HasComment("数独游戏版块大小");

                    b.Property<string>("StartBoard")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(1)
                        .HasComment("数独游戏开始时的版块");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(6)
                        .HasComment("数独游戏类型");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasComment("数独游戏更新时间");

                    b.Property<string>("WinBoard")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(3)
                        .HasComment("数独游戏获胜时的版块");

                    b.HasKey("Id");

                    b.ToTable("SudokuGames");
                });
#pragma warning restore 612, 618
        }
    }
}
